[helpers]
bool = ".dotter/helpers/bool.rhai"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/robbyrussell.zsh-theme" = "~/.oh-my-zsh/custom/themes/robbyrussell.zsh-theme"
"zsh/environment.sh" = "~/.config/environment.sh"
thefuck = "~/.config/thefuck/"
# local variable laptop

[alacritty.files]
alacritty = "~/.config/alacritty"

[kitty.files]
kitty = "~/.config/kitty"
"fastfetch/rin.png" = { target = "~/.config/fastfetch/rin.png", type = "symbolic" }
fastfetch = "~/.config/fastfetch"

[zellij.files]
zellij = "~/.config/zellij/"

[tui.files]
nvim = "~/.config/nvim"
ranger = "~/.config/ranger"
gitui = "~/.config/gitui"
# local variable laptop

[mpv.files]
mpv = "~/.config/mpv"

[music_manager.files]
music_manager = "~/.config/music_manager"

[wayfire.files]
swaylock = "~/.config/swaylock"
waybar = "~/.config/waybar"
wayfire = "~/.config"
rofi = "~/.config/rofi"

